name: Release

on:  
  release:
    types: [ published ]
  workflow_dispatch:

env:
  DOTNET_VERSION: 9.0.x
  CONFIGURATION: Release

jobs:
  nuget-org-push:
    runs-on: ubuntu-latest
    name: NuGet org push
    environment:
      name: "NuGetEnv"
      url: "https://www.nuget.org/packages/Arnab.CustomPrompt"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore
      run: dotnet restore --locked-mode

    - name: Build
      run: dotnet build -c ${{ env.CONFIGURATION }} --no-restore

    - name: Create nuget package
      run: | 
        dotnet pack "src/Arnab.CustomPrompt/Arnab.CustomPrompt.csproj" \
          -c ${{ env.CONFIGURATION }} \
          --no-restore \
          --no-build

    - name: Push nuget package
      run: |
        dotnet nuget push "src/Arnab.CustomPrompt/bin/Release/Arnab.CustomPrompt.0.0.4.nupkg" \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate
