name: Release

on:  
  release:
    types: [ published ]
  workflow_dispatch:

env:
  DOTNET_VERSION: 8.0.x
  CONFIGURATION: Release

jobs:
  build:    
    runs-on: ubuntu-latest   
    name: Build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Test
      run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-build

    - name: Create nuget package
      run: dotnet pack --configuration ${{ env.CONFIGURATION }}

  nuget-org-push:
    runs-on: ubuntu-latest
    needs: build
    name: NuGet org push
    environment:
      name: "NuGetEnv"
      url: "https://www.nuget.org/packages/Arnab.CustomPrompt"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }}

    - name: Create nuget package
      run: dotnet pack --configuration ${{ env.CONFIGURATION }}

    - name: Push nuget package
      run: |
        dotnet nuget push "src/Arnab.CustomPrompt/bin/Release/Arnab.CustomPrompt.0.0.2.nupkg" \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate