name: Release

on:  
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  nuget-org-push:
    runs-on: ubuntu-latest
    name: NuGet org push
    environment:
      name: "NuGetEnv"
      url: "https://www.nuget.org/packages/Arnab.CustomPrompt"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create package
      uses: ./.github/actions/create-package
      with:
        dotnet-version: 9.0.x

    - name: Push nuget package
      run: |
        dotnet nuget push "src/Arnab.CustomPrompt/bin/Release/Arnab.CustomPrompt.0.0.5.nupkg" \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate
